config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    resources :products
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  root "products#index"

  resources :carts do
    collection do
      post :checkout
    end
  end

  resources :orders do
    member do
      get :pay_with_credit_card
    end
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items, source: :product

  def add_product_to_me(product)
    items << product
  end

  def total_price
    items.inject(0) { |sum, product| sum + product.price }
    #sum = 0
    #items.each do | product|
    #  sum += product.price
    #end
    #sum
  end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product
end

app/models/order.rb
class Order < ActiveRecord::Base
  include AASM

  belongs_to :user

  has_one  :info, class_name: "OrderInfo", dependent: :destroy
  has_many :items, class_name: "OrderItem", dependent: :destroy

  accepts_nested_attributes_for :info

  before_create :generate_token

  def generate_token
    self.token = SecureRandom.uuid
  end

  def build_item_cache_from_cart(cart)
    cart.items.each do |cart_item|
      item = items.build
      item.product_name = cart_item.title
      item.quantity = 1
      item.price = cart_item.price
      item.save
    end
  end

  def calculate_total!(cart)
    self.total = cart.total_price
    self.save
  end

  def set_payment_with!(method)
    self.update_columns(payment_method: method)
  end

  def pay!
    self.update_columns(is_paid: true)
  end

  aasm do
    state :order_placed, initial: true
    state :paid
    state :shipping
    state :shipped
    state :order_cancelled
    state :good_returned

    event :make_payment, after_commit: :pay! do
      transitions from: :order_placed, to: :paid
    end

    event :ship do
      transitions from: :paid, to: :shipping
    end

    event :deliver do
      transitions from: :shipping, to: :shipped
    end

    event :return_good do
      transitions from: :shipped, to: :good_returned
    end

    event :cancel_order do
      transitions from: [:order_placed, :paid], to: :order_cancelled
    end
  end


end

app/models/order_info.rb
class OrderInfo < ActiveRecord::Base
  belongs_to :order

  validates :billing_name,     presence: true
  validates :billing_address,  presence: true
  validates :shipping_name,    presence: true
  validates :shipping_address, presence: true
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :product

  mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_one :photo
  accepts_nested_attributes_for :photo
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders

  def is_admin?
    is_admin
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  layout "admin"

  before_action :authenticate_user!
  before_action :admin_required

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    @photo = @product.build_photo
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path
    else
      render :new
    end

  end

  def edit
    @product = Product.find(params[:id])
    @photo = @product.photo
  end

  def update

    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  private
  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price,
      photo_attributes: [:id, :image])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_cart

  def admin_required
    if !current_user.is_admin?
      redirect_to root_path
    end
  end

  # a cart record, which is associated with the current user
  # return a cart instance
  def current_cart
    @current_cart ||= find_cart
  end

  private

  # find the cart, which is associated with the current user
  # if cart is allocated, session[:cart_id] = cart.id
  def find_cart

    cart = Cart.find_by(id: session[:cart_id])
    unless cart.present?
      cart = Cart.create
      session[:cart_id] = cart.id
    end

    cart
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, only: [:checkout]

  def index
  end

  def checkout
    @order = current_user.orders.build
    @info = @order.build_info
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def show
    #@order = Order.find(params[:id])
    @order = Order.find_by_token(params[:id])

    @order_info = @order.info
    @order_items = @order.items
  end

  def create
    @order = current_user.orders.build(order_params)

    if @order.save
      @order.build_item_cache_from_cart(current_cart)
      @order.calculate_total!(current_cart)

      #redirect_to order_path(@order)
      redirect_to order_path(@order.token)
    else
      render "carts/checkout"
    end
  end

  def pay_with_credit_card
    @order = Order.find_by_token(params[:id])
    @order.set_payment_with!("credit_card")

    #@order.pay!
    @order.make_payment!

    redirect_to "/", notice: "成功完成付款"

  end

  private

  def order_params
    params.require(:order).permit(info_attributes: [:billing_name,
                                                    :billing_address,
                                                    :shipping_name,
                                                    :shipping_address])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  # /products/:id/add_to_cart(.:format)
  def add_to_cart
    @product = Product.find(params[:id])

    if current_cart.items.include?(@product)
      flash[:warning] = "你的購物車內已有此物品"
    else
      current_cart.add_product_to_me(@product)
      flash[:notice] = "你已成功將 #{@product.title} 加入購物車"
    end

    redirect_to :back
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_message
    alert_types = {notice: :success, alert: :dnager}
    close_button_options = {class: "close", "data-dismiss" => "alert", "aria-hidden" => true}
    close_button = content_tag(:button, "x", close_button_options)

    alerts = flash.map do |type, message|
      alert_content = close_button + message

      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"

      content_tag(:fiv, alert_content, class: alert_class)
    end

    alerts.join("\n").html_safe
  end


  def render_cart_items_count(cart)
    cart.cart_items.count
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
    cart.total_price
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
<h2>Edit Product</h2>
<%= simple_form_for [:admin, @product] do |f| %>

  <div class="group">
    <%= f.input :title, label: "標題" %>
  </div>

  <div class="group">
    <%= f.input :description, label: "敘述" %>
  </div>

  <div class="group">
    <%= f.input :quantity, label: "數量" %>
  </div>

  <div class="group">
    <%= f.input :price, label: "價錢" %>
  </div>

  <div class="form-group">
    <%= f.simple_fields_for :photo do |c| %>
      <%= c.input :image, as: :file %>
    <% end %>
  </div>

  <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/admin/products/index.html.erb
<h2>Product List</h2>

<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("Add Product", new_admin_product_path, class: "btn btn-primary btn-sm") %>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th width="220">Product Pic</th>
      <th>Name</th>
      <th>Price</th>
      <th width="100">Options</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
    <tr>
      <td><%= product.id %></td>
      <td>
        <%= link_to(admin_product_path(product)) do %>
          <% if product.photo.present? %>
            <%= image_tag(product.photo.image.thumb.url, class: "thumbnail") %>
          <% else %>
            <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
          <% end%>
        <% end %>
      </td>
      <td><%= product.title %></td>
      <td><%= product.price %></td>
      <td><%= link_to("Edit", edit_admin_product_path(product)) %></td>
    </tr>
    <% end %>
  </tbody>

</table>

app/views/admin/products/new.html.erb
<h2>Add New Product</h2>
<%= simple_form_for [:admin, @product] do |f| %>

  <div class="group">
    <%= f.input :title, label: "標題" %>
  </div>

  <div class="group">
    <%= f.input :description, label: "敘述" %>
  </div>

  <div class="group">
    <%= f.input :quantity, label: "數量" %>
  </div>

  <div class="group">
    <%= f.input :price, label: "價錢" %>
  </div>

  <div class="form-group">
    <%= f.simple_fields_for :photo do |c| %>
      <%= c.input :image, as: :file %>
    <% end %>
  </div>

  <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/carts/checkout.html.erb
<div class="row">
  <div class="col-md-12">
  <h2>購物明細</h2>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th width="80%">商品明細</th>
        <th>單價</th>
      </tr>
    </thead>
    <tbody>
      <% current_cart.items.each do |product| %>
        <tr>
          <td>
            <%= link_to(product.title, product_path(product)) %>
          </td>
          <td>
            <%= product.price %>
          </td>
        </tr>
      <% end %>

    </tbody>

  </table>

  <div class="total clearfix">
    <span class="pull-right">
      Total: <%= render_cart_total_price(current_cart) %> NTD
    </span>
  </div>

  <hr>

  <h2>訂單資訊</h2>
  <div class="order-form">
    <%= simple_form_for @order do |f| %>
      <%= f.simple_fields_for :info do |c| %>
        <legend>訂購人</legend>
        <div class="form-group col-lg-6">
          <%= c.input :billing_name %>
        </div>
        <div class="form-group col-lg-6">
          <%= c.input :billing_address %>
        </div>

        <legend>收貨人</legend>
        <div class="form-group col-lg-6">
          <%= c.input :shipping_name %>
        </div>
        <div class="form-group col-lg-6">
          <%= c.input :shipping_address %>
        </div>

      <% end %>

      <%= f.submit "生成訂單", data: {disable_with: "Submitting..."},
                   class: "btn btn-lg btn-danger pull-right" %>
    <% end %>
  </div>

  </div>
</div>

app/views/carts/index.html.erb
<div class="row">
  <div class="col-md-12"></div>
  <h2>Shopping Cart</h2>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th colspan="2">Product Info</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% current_cart.items.each do |product| %>
        <tr>
          <td>
            <%= link_to(product_path(product)) do %>
              <% if product.photo.present? %>
                <%= image_tag(product.photo.image.thumb.url, class: "thumbnail") %>
              <% else %>
                <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail")%>
              <% end %>
            <% end %>
          </td>
          <td>
            <%= link_to(product.title, product_path(product)) %>
          </td>
          <td>
            <%= product.price %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <div class="total clearfix">
    <span class="pull-right">
      <span>總計 <%= render_cart_total_price(current_cart) %> NTD </span>
    </span>
  </div>

  <hr>

  <div class="checkout clearfix">
    <%= link_to("確認結賬", checkout_carts_path, method: :post,
                class: "btn btn-lg btn-danger pull-right") %>
  </div>
</div>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">EX-01</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to("Products", products_path) %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to(carts_path) do %>
            購物車 <i class="fa fa-shopping-cart"></i>
            (<%= render_cart_items_count(current_cart) %>)
          <% end %>
        </li>

        <% if !current_user %>
          <li> <%= link_to("註册", new_user_registration_path) %> </li>
          <li> <%= link_to("登入", new_user_session_path) %> </li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi!, <%= current_user.email %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if current_user.is_admin? %>
                <li><%= link_to("Admin ", admin_products_path) %></li>
              <% end %>
              <li>
                <%= link_to("登出", destroy_user_session_path, method: :delete ) %>
              </li>
            </ul>
          </li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>


<html>
<head>
  <title>ArtStore-01 Backend</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'dtat-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <div class="container">
    <%= render "common/navbar" %>
    <%= notice_message %>
    <div class="row">

      <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked" style="max-width: 300px;">
          <li><%= link_to("Product", admin_products_path) %></li>
        </ul>
      </div>

      <div class="col-md-10">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Artstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= render "common/navbar" %>
  <%= notice_message %>
  <%= yield %>
</div>

</body>
</html>

app/views/orders/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h2>訂單明細</h2>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th width="80%">Product Details</th>
          <th>Price</th>
        </tr>
      </thead>

      <tbody>
        <% @order_items.each do |order_item| %>
          <tr>
            <td>
              <%= order_item.product_name %>
            </td>
            <td>
              <%= order_item.price %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="total clearfix">
      <span class="pull-right">
        總計 <%= @order.total %> NTD
      </span>
    </div>

    <hr>

    <h2>寄送資訊</h2>

    <table class="table table-striped table-bordered">
      <tbody>
        <tr>
          <td>訂購人</td>
        </tr>
        <tr>
          <td><%= @order_info.billing_name %> - <%= @order_info.billing_address %> </td>
        </tr>
        <tr>
          <td>收件人</td>
        </tr>
        <tr>
          <td><%= @order_info.shipping_name %> - <%= @order_info.shipping_address %></td>
        </tr>
      </tbody>
    </table>

    <% if @order.is_paid? %>
      <p class="text-center">此訂單已完成付款</p>
    <% else %>
      <div class="pull-right">
        <%= link_to("以信用卡付款", pay_with_credit_card_order_path(@order.token), class: "btn btn-lg btn-danger") %>
        <%= link_to("以 ATM 付款", "#", class: "btn btn-lg btn-danger") %>
      </div>
    <% end %>


  </div>
</div>

app/views/products/index.html.erb
<div class="row">
  <% @products.each do |product| %>
    <div class="col-xs-6 col-md-3">

      <%= link_to(product_path(product)) do %>

        <% if product.photo.present? %>
          <%= image_tag(product.photo.image.thumb.url, class: "thumbnail") %>
        <% else %>
          <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
        <% end %>
      <% end %>

      <%= product.title %> $ <%= product.price %>
    </div>

  <% end %>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-6">
    <% if @product.photo.present? %>
      <%= image_tag(@product.photo.image.medium.url, class: "thumbnail") %>
    <% else %>
      <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
    <% end %>
  </div>

  <div class="col-md-6">
    <h2><%= @product.title %></h2>
    <div style="height:100px;">
      <p>
        <%= @product.description %>
      </p>
    </div>
    <div>數量 : <%= @product.quantity %></div>
    <div class="product-price"> $ <%= @product.price %></div>

    <div class="pull-right">
      <%= link_to("加入購物車",
                  add_to_cart_product_path(@product), method: :post,
                  class: "btn btn-primary btn-lg btn-danger") %>
    </div>
  </div>

</div>